import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { AnimatePresence } from "framer-motion";
import Link from "next/link";
import localFont from "next/font/local";
import Navbar from "./components/Navbar/navbar";

export const metadata: Metadata = {
  title: "Sweets",
  description: "Generated by Sweets Studio",
};

const pragati = localFont({
  src: [
    {
      path: "./fonts/PragatiNarrow-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pragati.className}`}>
        <div className="min-h-[100vh] max-w-[100vw] px-4 md:mx-auto grid-cols-13 grid gap-4 md:gap-8 grid-rows-7 max-h-[100vh]">
          <Navbar/>
          {children}
        </div>
      </body>
    </html>
  );
}
