import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { AnimatePresence } from "framer-motion";
import Link from "next/link";
import localFont from "next/font/local";


export const metadata: Metadata = {
  title: "Sweets",
  description: "Generated by Sweets Studio",
};


const pragati = localFont({
  src: [
    {
      path: "./fonts/PragatiNarrow-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pragati.className}`}>{children}</body>
    </html>
  );
}
