import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { AnimatePresence } from "framer-motion";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
